//HintName: T.ValueItem_Generated.cs
// <auto-generated />

using System;
using System.Buffers.Binary;

namespace T
{
    readonly ref partial struct ValueItem
    {
        private readonly Span<byte> _span;

        /// <summary>
        /// Defines the minimum possible size of this packet, given all
        /// known fixed sizes.
        /// </summary>
        public const int MinimumSize = sizeof(int);

        public ValueItem(Span<byte> packetData)
        {
            _span = packetData;
        }

        public Span<byte> GetRawData() => _span;

        
        
        public T.TcpFlags Value
        {
           get => (T.TcpFlags)(BinaryPrimitives.ReadInt32BigEndian(_span.Slice(0)));
           set => BinaryPrimitives.WriteInt32BigEndian(_span.Slice(0), (int)(value)); 
        }
        
    }
}
