//HintName: T.ValueItem_Generated.cs
// <auto-generated />

using System;
using System.Buffers.Binary;

namespace T
{
    readonly ref partial struct ValueItem
    {
        private readonly Span<byte> _span;

        /// <summary>
        /// Defines the minimum possible size of this packet, given all
        /// known fixed sizes.
        /// </summary>
        public const int MinimumSize = 6 + sizeof(ushort) + sizeof(ushort);

        /// <summary>
        /// Create a new instance of <see cref="ValueItem"/>.
        /// </summary>
        public ValueItem(Span<byte> packetData)
        {
            _span = packetData;
        }

        /// <summary>
        /// Gets the raw underlying buffer for this packet.
        /// </summary>
        public Span<byte> GetRawData() => _span;
        
        
        public ushort Value
        {
           get => BinaryPrimitives.ReadUInt16BigEndian(_span.Slice(6));
           set => BinaryPrimitives.WriteUInt16BigEndian(_span.Slice(6), value); 
        }
        
        
        public ushort NextValue
        {
           get => BinaryPrimitives.ReadUInt16BigEndian(_span.Slice(T.PacketDefinition.GetNextValuePosition(_span, 6 + sizeof(ushort))));
           set => BinaryPrimitives.WriteUInt16BigEndian(_span.Slice(T.PacketDefinition.GetNextValuePosition(_span, 6 + sizeof(ushort))), value); 
        }
        
        /// <summary>
        /// Get a string representation of this packet.
        /// </summary>
        public override string ToString()
        {
            return $"Value: {Value}; NextValue: {NextValue}";
        }

        /// <summary>
        /// Get the computed total size of this packet, including any dynamically-sized fields and trailing payloads.
        /// </summary>
        public int GetTotalSize()
        {
            return T.PacketDefinition.GetNextValuePosition(_span, 6 + sizeof(ushort)) + sizeof(ushort);
        }
    }
}
