// <auto-generated />

using System;

namespace Enclave.FastPacket.Generator
{
    [AttributeUsage(AttributeTargets.Property)]
    internal sealed class PacketFieldAttribute : Attribute
    {
        public int Size { get; set; }

        public int Position { get; set; }

        public string? PositionFunction { get; set; }

        public Type? EnumBackingType { get; set; }
    }
}
